---
name: cahubshot
description: CodeArise HUB Shot
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  meta: ^1.3.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.7
  firebase_core: ^1.14.0
  firebase_analytics: ^9.1.4
  firebase_auth: ^3.3.13
  firebase_storage: ^10.2.11
  flutter_bloc: ^7.3.3
  equatable: ^2.0.3
  image_cropper: ^1.4.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  timeago: ^3.0.2
  uuid: ^3.0.6
  bot_toast: ^4.0.1
  font_awesome_flutter: ^10.1.0
  flutter_web_browser: ^0.17.0
  image_downloader: ^0.31.0
  share_plus: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
  flutter_launcher_icons: "^0.9.1"

  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/insta.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/auth/